// INCLUDE FILE generated by "Pelles C for Windows, version 4.00".

/*----- frmMain -----*/
#define FRM_MAIN					1001
#define TAB_CONTROL_1_PAGE_1		1002
#define TAB_CONTROL_1_PAGE_2		1003
#define TAB_CONTROL_1_PAGE_3		1004
#define TAB_CONTROL_1_PAGE_4		1005

#define TAB_CONTROL_2_PAGE_1		1006
#define TAB_CONTROL_2_PAGE_2		1007
#define TAB_CONTROL_2_PAGE_3		1008
#define TAB_CONTROL_2_PAGE_4		1009



#define MNU_MAIN					2001
#define MNU_ABOUT					2002
#define MNU_FILE					2007
#define MNU_QUIT					2013

#define IDC_EDIT_URL				3001

#define TAB_CONTROL_1				4001
#define FRA_TAB_PAGE_2				4002
#define FRA_TAB_PAGE_3				4003
#define FRA_TAB_PAGE_4				4004

#define CMD_CLICK_1					4005
#define CMD_CLICK_2					4006
#define CMD_CLICK_3					4007

#define CMD_CLICK_4					4008
#define CMD_CLICK_5					4009
#define LBL_1						4010

#define CMD_CLICK_6					4011
#define CMD_CLICK_7					4012
#define LBL_2						4013



#define MAIN_WEB_TAB_CONTROL		4014
#define FRA_TAB_PAGE_5				4015
#define FRA_TAB_PAGE_6				4016
#define FRA_TAB_PAGE_7				4017
#define FRA_TAB_PAGE_8				4018

#define CMD_CLICK_8					4019
#define CMD_CLICK_9					4020

#define LBL_3						4021

#define IDC_BUTTON_RUNURL			4022
#define IDC_BUTTON_GOFORWARD		4023
#define IDC_BUTTON_GOBACK			4024
#define IDC_BUTTON_FLUSH			4025
#define IDC_BUTTON_CLOSE			4026
#define IDC_BUTTON_STOP				4027

#define IDR_ICO_MAIN  				8001
